# Generated by Django 4.0.1 on 2022-01-22 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgs', '0002_alter_image_preds'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='preds',
            new_name='tess_preds',
        ),
        migrations.AddField(
            model_name='image',
            name='my_preds',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
